services:
  swagger:
    image: 'docker.swagger.io/swaggerapi/swagger-ui'
    environment:
      - 'SWAGGER_JSON=/home/swagger.json'
    volumes:
      - ./swagger.json:/home/swagger.json
    ports:
      - '80:8080'
